[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "flask",
    "flask-smorest",
]
description = "Your first Python API; Flask edition"
readme = "README.md"
keywords = ["flask", "API", "SPUG", "meetup", "example"]
license = { file = "LICENSE" }
name = "spug-flask"
version = "0.1.0"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
flask-api = "app.app:main"

[project.optional-dependencies]
dev = [
    "bandit",
    "ruff",
    "setuptools",
    "types-python-dateutil",
    "types-requests",
    "typing-extensions",

]
docker = [
    "gunicorn",
]

[tool.bandit]
exclude_dirs = [
    "tests", "venv"
    ]
skips = ["B311"]


[tool.ruff]
exclude = [
    "tests",
    "venv"
]
line-length = 120


[tool.setuptools]
package-dir = {"" = "src"}
packages = ["app"]
